# Generated by Django 3.0.5 on 2021-03-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participnats',
            new_name='participants',
        ),
    ]
